### ISSUE TITLE
is there any editor text change event triggered?

### ISSUE THREAD

**Issue by jstdoit** [nnhubbard/ZSSRichTextEditor#5]
how can I detect the text change event?

**Comment by william205** [comment]
@richardortiz84 I have added your solution to the source and will push it to Github soon.

**Comment by MadeByDouglas** [comment]
Anyone here still interested in this project? So I've rewritten this using `WKWebView` instead of `UIWebView` and this section is the only part that remains. I'm not familiar with this JS context idea `[webView valueForKeyPath:@"documentView.webView.mainFrame.javaScriptContext"];` what is the proper approach to refactor this to use `WKScriptMessage` as described in a general way in the SO link? https://stackoverflow.com/questions/25792131/how-to-get-jscontext-from-wkwebview

**Comment by MadeByDouglas** [comment]
I figured it out https://github.com/nnhubbard/ZSSRichTextEditor/pull/243
